# RESIZE ONLY REQUIRED DIMENSION
# HEIGHT IS CHANGED BUT WIDTH IS UNCHANGED (9-resize.py)

# RESIZE WITH BOTH INPUTS
# BOTH WIDTH AND HEIGHT ARE CHANGED (9-resize.py)

# RESIZING BASED ON THE ASPECT RATIO
# SCALING UP - ZOOMING IN
# SCALING DOWN - SHRINKING OUT

# BASED ON ASPECT RATIO
# 1. INTERPOLATION CUBIC - INTER_CUBIC
# 2. INTERPOLATION LINEAR - INTER_LINEAR
# 3. INTERPOLATION AREA - INTER_AREA
# 4. INTERPOLATION NEAREST - INTER_NEAREST

