"""
UNDERSTAND CONCEPT AND LOGIC
PRACTICE
SYNTAX AND BASICS
PROBLEM STATEMENTS SOLVING
- STACK OVERFLOW, GITHUB WILL HELP YOU.
KEEP IT SIMPLE, AND READABLE.
USE COMMENTS.
------------------------------------------
SOLVE PROBLEMS -->
1. BREAK THE PROBLEM INTO PARTS
2. USE FLOWCHARTS.
3. SOLVE LOGICAL PROBLEMS
4. WORK ON PROJECTS
------------------------------------------
1. USE SIMPLE AND PROPER NAMES
2. Write variables like this - x = 1.
3. Proper way to define class - class Post
4. AVOID REDUNDANT PARENTHESIS.
"""